spring:
  application:
    name: eureka-web
    
server:
  port: 8072

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
     